### ISSUE TITLE
Incorrect digit returned in calculaMod11

### ISSUE THREAD

**Issue by JohnKevid** [Philippenau-Dev/boleto_utils#1]
In the function calculaModulo11 in boleto.dart file, you need to change from:

```
if (int.parse(digito) < 2) {
  digito = '1';
} else if (int.parse(digito) >= 2) {
  digito = (11 - int.parse(digito)).toString();
}

return digito;
```

To:

```
if (int.parse(digito) < 2) {
  digito = '0';
} else if (int.parse(digito) >= 2) {
  digito = (11 - int.parse(digito)).toString();
}

return digito;
```

The digit needs to be 0 when `int.parse(digito) < 2)`.

Accordingly with the doc
https://cmsarquivos.febraban.org.br/Arquivos/documentos/PDF/Layout%20-%20C%C3%B3digo%20de%20Barras%20ATUALIZADO.pdf

**Comment by Philippenau-Dev** [comment]
fixed digit that is returned when less than 2 or equal to 10
