### ISSUE TITLE
Correção validar codigo de barras com mod11

### ISSUE THREAD

**Issue by gonzalesMK** [Philippenau-Dev/boleto_utils#3]
https://github.com/Philippenau-Dev/boleto_utils/blob/1afda9d94603646cafeb26982c760ab39720d792/lib/src/boleto.dart#L545C1-L548C18

Conforme esse manual: 

https://s3.sa-east-1.amazonaws.com/static.bancointer.com.br/openbanking/cnab/manual/manual.pdf

Entendo que o código correto para validar boletos com mod11 seja esse:
```dart
    if (digito < 2) {
      digito = 1;
    } else if (digito == 10) {
      digito = 1;
```

**Comment by maurojohann** [comment]
@gonzalesMK  Acredito que esse documento do Inter não tem referencia ao modulo11.
Mas olhando a regra do modulo 11 da FENABRAN que está na imagem abaixo, o calculo está correto. 
"Quando o resto da divisão for igual a 0 ou 1, atribuí-se ao DV o digito “0” "
<img width="687" alt="image" src="https://github.com/user-attachments/assets/321ac831-123b-44f2-b787-531e62181c13">
